#!/bin/bash

#/ NAME
#/     build -- builds macports, ports
#/           -- builds static site using jekyll
#/
#/ SYNOPSIS
#/     build macports|ports
#/     build site

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"

# load a meat library
source "$shome/libexec/_jason" "$@"

DEFINE_boolean reinstall "$FLAGS_FALSE" "reinstall rubies"

# entry point
function mpmain {
  local cmd_install
  if [[ "$FLAGS_reinstall" = "$FLAGS_TRUE" ]]; then
    cmd_install="reinstall"
  else
    cmd_install="install"
  fi

  local nm_ruby
  for nm_ruby in "$@"; do
    case $nm_ruby in
      ree)
        rvm $cmd_install $nm_ruby --with-openssl=$MACPORTS
        ;;
      1.9.3)
        rvm $cmd_install $nm_ruby --with-opt-dir=$MACPORTS
        ;;
      *)
        rvm $cmd_install $nm_ruby
        ;;
    esac
  done
}

require macports "$BASH_SOURCE" "$@"
