#!/bin/bash

#/ NAME
#/     setup -- one time setup for xcode
#/
#/ SYNOPSIS
#/     setup homebrew

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"

# load a meat library
source "$shome/libexec/_prime" "$@"
require 'homebrew_profile'

# define command line options:
#   var name, default, description, short option
DEFINE_string 'install' "${HOMEBREW:-$shome/local}" 'homebrew install' 'I'

# entry point
function main {
  export HOMEBREW="$FLAGS_install"

  dir_software="${HOMEBREW//\//_}"
  mkdir -p "$shome/vault/homebrew/distfiles"
  mkdir -p "$shome/vault/homebrew/software/$dir_software"
  mkdir -p "$HOMEBREW"
  ln -vnfs "$shome/vault/homebrew/software/$dir_software" "$HOMEBREW/software"

  mkdir -p "$HOMEBREW/bin"
  ln -nfs $shome/bin/brew $HOMEBREW/bin/
  rsync -ia $shome/share $HOMEBREW/
  mkdir -p $HOMEBREW/Library/LinkedKegs
  set +f
  for nm_lib in $(ls -d $shome/Library/* | grep -v '/LinkedKegs$'); do
    nm_lib=${nm_lib##*/}
    ln -nfs $shome/Library/$nm_lib $HOMEBREW/Library/
  done
  set -f
}

require sub "$BASH_SOURCE" "$@"
